---
title: "My Statistical Bookshelf"
editor: visual
toc: false
---

Keep up with my reading habits! Feel free to [email](mailto:kevinbaer@ucla.edu){target="_blank"} me recommendations! (Last updated: September 4th, 2025)

### Currently Reading:

-   ⭐ **An Introduction to Statistical Learning in R (ISLR)** by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani

    -   Accompanied by: **ISLR tidymodels labs** by Emil Hvitfeldt

### In Progress:

-   **Python Polars: The Definitive Guide** by Jeroen Janssens and Thijs Nieuwdorp

-   **Data Science for Business** by Foster Provost and Tom Fawcett

-   **Spatio-Temporal Statistics with R** by Christopher Wikle, Andrew Zammit-Mangion, and Noel Cressie

-   **The Visual Display of Quantitative Information** by Edward Tufte

### Past Favorites (in rough order by frequence of reference):

-   **Tidy Modeling with R** by Max Kuhn and Julia Silge

-   **Mastering Shiny** by Hadley Wickham

-   **ggplot2: Elegant Graphics for Data Analysis** by Hadley Wickham, Danielle Navarro

-   **Class Notes - Intro To Database Systems** **(CMU 15-445/645 - Fall 2024)** by Andy Pavlo

-   **Advanced R** by Hadley Wickham

-   **R for Data Science** by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund

-   **Class Notes - Introduction to Data Analysis and Regression** (**UCLA Stats 101a - Spring 2025)** by Robert Gould

-   **Class Notes - Python and Other Technologies for Data Science (UCLA Stats 21 - Fall 2024)** by Miles Chen

-   **SQL for Data Scientists** by Renée Teat

-   **Class Notes -** **Introduction to Statistical Programming with R** **(UCLA Stats 20 - Spring 2024)** by Mike Tsiang

-   **Class Notes - Introduction to Probability (UCLA Stats 100a - Spring 2025)** by Ying Nian Wu

### Waiting For Their Moment:

-   **Bayes Rules!** by Alicia Johnson, Miles Ott, and Mine Dogucu

    -   Accompanied by: **Bayesf22 Notebook** by Andrew Heiss

-   **Beyond Multiple Linear Regression** by Paul Roback and Julie Legler

-   **Handbook of Spatial Statistics** by Alan Gelfand, Peter Diggle, Peter Guttorp, and Montserrat Fuentes

-   **Storytelling with Data: A Data Visualization Guide for Business Professionals** by Cole Nussbaumer Knaflic

-   **Happy Git and GitHub for the useR** by Jenny Bryan

-   **Outstanding User Interfaces with Shiny** by David Granjon

-   **Fluent Python** by Luciano Ramalho

-   **Efficient Machine Learning with R** by Simon Couch

-   **Applied Machine Learning for Tabular Data** by Max Kuhn and Kjell Johnson

-   **The Programmer's Brain** by Felienne Hermans

-   **Feature Engineering A-Z** by Emil Hvitfeldt

-   **Feature Engineering and Selection: A Practical Approach for Predictive Models** by Max Kuhn and Kjell Johnson

-   **Statistical Rethinking: A Bayesian Course with Examples in R and Stan** by Richard McElreath

-   **Probabilistic Machine Learning: An Introduction** by Kevin Murphy

-   **The Elements of Statistical Learning** by Trevor Hastie, Robert Tibshirani, and Jerome Friedman

-   **The StatQuest Illustrated Guide To Machine Learning** by Josh Starmer

-   **Class Notes - Foundations of Machine Learning (Bloomberg ML EDU)** by David Rosenberg

-   **Supervised Machine Learning for Science** by Cristoph Molnar and Timo Freiesleben

-   **Probability Theory: The Logic of Science** by E.T. Jaynes

-   **Bayesian Sports Models in R** by Andrew Mack

-   **Class Notes - Advanced Database Systems (CMU 15-721 Spring 2024)** by Andy Pavlo

-   **Linear Model and Extensions** by Peng Ding
