project:
  type: website
  output-dir: docs

website:
  title: "Kevin Baer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - bdb24.qmd
      - nflpa24.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

